added docker and docker-compose check in talk executable

diff --git a/talk b/talk
--- a/talk
+++ b/talk
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+if ! [ -x "$(command -v docker)" ]; then
+  echo 'Error: docker is not installed.' >&2
+  exit 1
+fi
+
+if ! [ -x "$(command -v docker-compose)" ]; then
+  echo 'Error: docker-compose is not installed.' >&2
+  exit 1
+fi
+
 if [ $# -eq 0 ]; then
     echo "No command found"
     exit
